### ISSUE TITLE
Website Is Unreachable

### ISSUE THREAD

**Issue by ccunni3** [garfix/architectural-patterns#2]
I saw in the source for dossier-andres.net that there is a new site for the software architecture section. When I tried to go to the new site I see that the server is unreachable.

Output from `curl https://architectural-patterns.net`:
```
curl: (7) Failed to connect to architectural-patterns.net port 443 after 7173 ms: Couldn't connect to server
```

Output from `dig architectural-patterns.net`:
```
; <<>> DiG 9.10.6 <<>> architectural-patterns.net
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 8346
;; flags: qr rd ra ad; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1232
;; QUESTION SECTION:
;architectural-patterns.net.	IN	A

;; ANSWER SECTION:
architectural-patterns.net. 3600 IN	A	136.144.240.141

;; Query time: 211 msec
;; SERVER: 1.1.1.1#53(1.1.1.1)
;; WHEN: Wed Aug 14 15:22:05 CDT 2024
;; MSG SIZE  rcvd: 71
```

**Comment by garfix** [comment]
Hi Cole, thanks for reporting it to me! 

I had no idea the server was down. For 4 days already. I just restarted it. I tried to check the logs to see what went wrong, but couldn't find anything.
